/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9d7',
        'on-secondary-fixed': '#2a1800',
        'surface': '#fcf9f6',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffddb5',
        'background': '#fcf9f6',
        'surface-container-high': '#ebe7e5',
        'on-surface-variant': '#4c4734',
        'tertiary': '#655f3e',
        'on-secondary-fixed-variant': '#643f00',
        'inverse-on-surface': '#f3f0ee',
        'secondary-container': '#ffb13e',
        'on-primary-fixed': '#221b00',
        'primary-fixed-dim': '#e6c42c',
        'surface-container-highest': '#e5e2e0',
        'secondary-fixed-dim': '#ffb958',
        'primary-fixed': '#ffe16b',
        'on-error': '#ffffff',
        'on-secondary-container': '#6f4600',
        'surface-variant': '#e5e2e0',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#4d4728',
        'primary': '#6f5d00',
        'on-primary-fixed-variant': '#544600',
        'outline-variant': '#cfc6ad',
        'text-secondary': '#2c2c29',
        'on-background': '#1c1c1a',
        'on-tertiary-fixed': '#201c03',
        'secondary': '#845400',
        'outline': '#7e7761',
        'status-success': '#2b9146',
        'primary-container': '#ffdc44',
        'surface-white': '#ffffff',
        'status-draft': '#ff60b5',
        'error': '#ba1a1a',
        'inverse-primary': '#e6c42c',
        'surface-bright': '#fcf9f6',
        'error-container': '#ffdad6',
        'on-primary-container': '#736000',
        'on-surface': '#1c1c1a',
        'on-tertiary-container': '#686240',
        'surface-container': '#f0edeb',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#d0c79f',
        'surface-container-low': '#f6f3f1',
        'tertiary-fixed': '#ece3b9',
        'status-accent': '#7160ff',
        'tertiary-container': '#e8deb4',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#31302f',
        'surface-tint': '#6f5d00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'base': '4px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['"Be Vietnam Pro"', 'sans-serif'],
        'headline-lg': ['"Be Vietnam Pro"', 'sans-serif'],
        'headline-lg-mobile': ['"Be Vietnam Pro"', 'sans-serif'],
        'headline-md': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-lg': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-md': ['"Be Vietnam Pro"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.03em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
